language: bash

services:
  - xvfb

addons:
  apt:
    packages:
      - wget
      - unzip
      - xfce4
      - xfce4-terminal
      - chrome-remote-desktop

before_install:
  - echo "Installing Chrome Remote Desktop and XFCE..."
  - sudo apt update
  - wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
  - sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt -f install -y
  - sudo apt install -y xfce4 xfce4-goodies desktop-base
  - echo "xfce4-session" > ~/.chrome-remote-desktop-session
  - chmod +x ~/.chrome-remote-desktop-session
  - sudo systemctl enable chrome-remote-desktop

install:
  - echo "Setting up Chrome Remote Desktop..."
  - wget -qO- https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome-remote-desktop/deb/ stable main" | sudo tee /etc/apt/sources.list.d/chrome-remote-desktop.list
  - sudo apt update
  - sudo apt install -y chrome-remote-desktop

script:
  - echo "Starting Chrome Remote Desktop..."
  - sudo systemctl start chrome-remote-desktop
  - echo "RDP setup complete. Access it via Chrome Remote Desktop on your Google Account."

after_success:
  - echo "Pipeline executed successfully."
  
