apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: my-vm
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
          - name: disk0
            disk:
              bus: virtio
        resources:
          requests:
            memory: 1024Mi
      volumes:
      - name: disk0
        containerDisk:
          image: kubevirt/cirros-container-disk-demo
          
